### ISSUE TITLE
How can I get an explanation from a single feature x1 or binary features (x1, x2)？

### ISSUE THREAD

**Issue by 775269512** [facebookresearch/nbm-spam#16]
How can I get Shape function visualization through heatmaps from the sub-nn?
I like your work very much, If you can provide the code of shape functions, thank you very much!!!!!

**Comment by filipradenovic** [comment]
Take a look at this example from NAM github project: `https://github.com/AmrMKayid/nam/blob/main/nam/utils/graphing.py`. It is build for NAM but it can work for any GAM-based model, including NBM.

**Comment by 775269512** [comment]
Thank you very much for your suggestion, it solved my problem.
Also I have two small questions.
1. NBM is the feature contribution degree obtained by parameter sharing, does it mean that there is only one f_i() to decompose all feature domains
2. want to know in advance if this article is accepted neurips？

thx u ans！！！
