### ISSUE TITLE
Further visualization details about NBM

### ISSUE THREAD

**Issue by 775269512** [facebookresearch/nbm-spam#17]
Thank you for your reply regarding the visualization of interpretable GAM-based questions, and here are some small questions about how NBM is visualized.
1. NBM gets the contribution on different feature domains by means of parameter sharing, does it mean that there is only one F_i() function that operates on all features. Is this non-separation of contribution degrees trustworthy.
2. How to handle the value of B in F_ib() by summing or averaging?

Congratulations on being accepted by nuerips22, it is a useful work to implement NAM by reducing the dimensional explosion of parameters.
Due to my stupidity, I would like to know more details about the visualization and learn from you.

**Comment by filipradenovic** [comment]
1. There is B basic functions that operate on all features, and weighted combination of those basis functions is F_i() so there will be a different F_i() for each input feature, see Fig. 3 in https://arxiv.org/pdf/2205.14120.pdf. So you will get a contribution for each feature, and it will be trustworthy, ie it will describe exactly how the model makes prediction.
2. For visualizing, you can ignore B and F_ib(), basis themselves are not strictly interpretable. Visualize just the final function F_i(), this is the interpretable shape function per input feature of the model.

**Comment by 775269512** [comment]
Thank you for your reply, it solved my problem!
