### ISSUE TITLE
Unable to understand the last term of the proof

### ISSUE THREAD

**Issue by 775269512** [facebookresearch/nbm-spam#18]
You have provided detailed proofs in the appendix and they are very impressive, but I cannot understand why $2\sqrt{\frac{\log(2/\delta )}{n}}$ + $\sqrt{\frac{8\log(4/\delta )}{n}}$ =? $5\sqrt{\frac{\log(4/\delta )}{n}}$. Is something wrong?

Also, I'm not quite sure why $2\sqrt{\frac{\log(2/\delta )}{n}}$ can be obtained by the Azuma-Hoeffding inequality 
Thank you so much if you can answer them, your work is wonderful and can provide a lot of theoretical evidence for GAMs!

**Comment by abhimanyudubey** [comment]
Hi, thanks for your appreciation of our work. 

Regarding 1): Observe that $2\sqrt{\frac{\log(2/\delta )}{n}} < 2\sqrt{\frac{\log(4/\delta )}{n}}$ and  $\sqrt{\frac{8\log(4/\delta )}{n}} = 2\sqrt{\frac{2\log(4/\delta )}{n}} < 3\sqrt{\frac{\log(4/\delta )}{n}}$. Adding them together gives the result.

Regarding 2): This is a standard bound obtained by Azuma's inequality (see https://en.wikipedia.org/wiki/Azuma%27s_inequality) and substituting the RHS probability with $\delta$. By the inequality, we have that with probability $1-\delta$ the error term is bounded by $\epsilon$, which can be rewritten in terms of $\delta$ giving us the final form of the equation.

**Comment by 775269512** [comment]
i see! thank u for your patience~
